Question:1

In [10]:
from array import array
arra1 = array('H', [1,2,3,4,5,6,7,8,9])
print("Original array: ")
print(arra1)
print("Array to list: ")
print(arra1.tolist())

Original array: 
array('H', [1, 2, 3, 4, 5, 6, 7, 8, 9])
Array to list: 
[1, 2, 3, 4, 5, 6, 7, 8, 9]


Question:2

In [16]:
import numpy as np
m = np.arange(9).reshape(3,3)
print("Original matrix:")
print(m)
result =  np.trace(m)
print("Condition number of the said matrix:")
print(result)

Original matrix:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Condition number of the said matrix:
12


Question:3

In [2]:
import numpy as np

x = np.array([[0, 10, 20], [20, 30, 40]])
print("Original array: ")
print(x)
print("Values bigger than 10 =", x[x>10])
print("Their indices are ", np.nonzero(x > 10))

Original array: 
[[ 0 10 20]
 [20 30 40]]
Values bigger than 10 = [20 20 30 40]
Their indices are  (array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))


Question:4

In [40]:
import numpy as np
a = np.array([[0, 10, 20] , [20, 30, 40]])
b = np.array([[0, 10, 20] , [20, 30, 40]])


for i in range (len(a)):
    c=a[:,:]+b[:,:]
    
print(c)


#c=a+b

""""z=(a[0,0])+(b[0,0])
e=(a[0,1])+(b[0,1])
r=(a[0,2])+(b[0,2])

t=(a[1,0])+(b[1,0])
y=(a[1,1])+(b[1,1])
u=(a[1,2])+(b[1,2])

c=(z,e,r,t,y,u)

print(c)"""



[[ 0 20 40]
 [40 60 80]]


'"z=(a[0,0])+(b[0,0])\ne=(a[0,1])+(b[0,1])\nr=(a[0,2])+(b[0,2])\n\nt=(a[1,0])+(b[1,0])\ny=(a[1,1])+(b[1,1])\nu=(a[1,2])+(b[1,2])\n\nc=(z,e,r,t,y,u)\n\nprint(c)'

Question:5

In [14]:
import numpy as np
print("Original matrix")
X = np.random.rand(3, 6)
print(X)
print("Subtract the mean of each row of the said matrix:")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix
[[0.28656937 0.85934837 0.7826951  0.74030761 0.88949159 0.79087783]
 [0.46486184 0.97340973 0.9574023  0.6917564  0.7783304  0.34353612]
 [0.22288618 0.02418203 0.48711731 0.87126926 0.22769173 0.3456935 ]]
Subtract the mean of each row of the said matrix:
[[-0.43831228  0.13446673  0.05781346  0.01542596  0.16460995  0.06599618]
 [-0.23668763  0.27186027  0.25585283 -0.00979307  0.07678093 -0.35801334]
 [-0.14025383 -0.33895797  0.12397731  0.50812926 -0.13544827 -0.0174465 ]]
